name: Build and Push to DockerHub
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64, linux/arm/v7, linux/arm/v8, linux/arm64
          tags: logzio/logzio-api-fetcher:latest, logzio/logzio-api-fetcher:${{ github.event.release.tag_name }}
